#! /bin/sh

sed -i 's/autohide="top"/autohide="off"/g' $HOME/.jwm/panel/tray &
sed -i 's/autohide="bottom"/autohide="off"/g' $HOME/.jwm/tray2 &
sleep 0.2s
cp -a $HOME/.jwm/panel/tray $HOME/.jwm/tray &
sh "$HOME/.jwm/restart" &